security:
    # Stratégie de hachage des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Source des utilisateurs (ta table MySQL 'user')
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Hiérarchie : L'Admin possède par défaut tous les droits du Bureau
    role_hierarchy:
        ROLE_SUPER_ADMIN: ROLE_ADMIN # Le Président (Super Admin) a les droits du Bras Droit (Admin) + du Staff
        ROLE_ADMIN: ROLE_USER # Le Bras Droit (Admin) a les droits du Staff (User)

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        # 1. PARE-FEU POUR LE LOGIN (Génération du jeton)
        # On intercepte les requêtes sur /api/login pour créer le JWT
        login:
            pattern: ^/api/login
            stateless: true # Mode pro : le serveur ne stocke aucune session
            json_login:
                check_path: api_login
                username_path: email
                password_path: password
                # Ces gestionnaires de Lexik renvoient le JSON {"token": "..."} automatiquement
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # 2. PARE-FEU PRINCIPAL (Vérification du jeton)
        # Toutes les autres requêtes passant par /api seront vérifiées
        main:
            pattern: ^/api
            stateless: true # Indispensable pour le mode JWT
            jwt: ~ # Active la lecture du jeton "Authorization: Bearer <token>"

    # 3. CONTRÔLE D'ACCÈS (Tes règles métier)
    access_control:
        # La route de login doit être publique pour pouvoir se connecter !
        - { path: ^/api/login, roles: PUBLIC_ACCESS }

        # Seul l'ADMIN peut voir les adhérents HelloAsso et gérer les invitations
        - { path: ^/api/admin/subscribers, roles: ROLE_ADMIN }
        - { path: ^/api/admin/invitations, roles: ROLE_ADMIN }
        - { path: ^/api/admin/users, roles: ROLE_ADMIN } 
        
        # Le reste de l'admin est accessible au BUREAU (ROLE_USER) et à l'ADMIN
        - { path: ^/api/admin, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10