security:
    # Stratégie de hachage des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Définit où Symfony va chercher les utilisateurs pour les authentifier
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Hiérarchie : L'Admin possède par défaut tous les droits du Bureau
    role_hierarchy:
        ROLE_SUPER_ADMIN: ROLE_ADMIN    # ---Le Président (Super Admin) a les droits du Bras Droit (Admin) + du Staff
        ROLE_ADMIN: ROLE_USER           # ---Le Bras Droit (Admin) a les droits du Staff (User)
    
    # Firewall : Définit les règles de sécurité pour les différentes parties de l'application
    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
            
        # --- Le Webhook HelloAsso (public) ---
        webhook:
            pattern: ^/api/webhook/helloasso
            stateless: true
            security: false # ---On désactive la sécurité pour cette route précise, car HelloAsso ne peut pas gérer les jetons JWT. C'est un webhook public qui reçoit des notifications de HelloAsso, donc il doit être accessible sans authentification.

        # --- Vérification adhésion (public) ---    
        membership_check:  
            pattern: ^/api/membership/check # -- Route publique qui vérifie si une personne est adhérente
            stateless: true
            security: false


        # ---  Le Login (génère le JWT) ---
        login:
            pattern: ^/api/login
            stateless: true # Mode pro : le serveur ne stocke aucune session
            json_login:
                check_path: api_login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success    # Si email + password OK → LexikJWT génère et renvoie un token JWT
                failure_handler: lexik_jwt_authentication.handler.authentication_failure    # Si email ou password incorrect → renvoie 401 Unauthorized

        # --- Toutes les autres routes /api/* ---
        main:
            pattern: ^/api
            stateless: true         # Indispensable pour le mode JWT
            jwt: ~                  # Active la lecture du jeton "Authorization: Bearer <token>"

    # CONTRÔLE D'ACCÈS (Régles d'accés par URL)
    access_control:
        # --- Routes publiques (sans token JWT)
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/membership/check, roles: PUBLIC_ACCESS }

        # ---Routes réservées à l'ADMIN (Bras Droit + Président)
        - { path: ^/api/admin/subscribers, roles: ROLE_ADMIN }  
        - { path: ^/api/admin/invitations, roles: ROLE_ADMIN }
        - { path: ^/api/admin/users, roles: ROLE_ADMIN } 
        
        # --- Reste de l'admin → ROLE_USER (tout le bureau)
        - { path: ^/api/admin, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10