export * from './Home/HomePage';
export * from './About/AboutPage';
export * from './Membership/MembershipPage';
export * from './News/NewsPage'; 
export * from './News/NewsDetailPage';
export * from './Events/EventsPage'; 
export * from './Contact/ContactPage';
export * from './Register/RegistrationPage';
export * from './Register/ForgotPasswordPage';
